services:
  client-analysis:
    image: riccardidario1/client:latest
    container_name: client_analysis
    volumes:
      - ./output:/app/output
      - ./certs:/opt/certs
      - ./tls_keys:/tls_keys
      - ./start_client.py:/app/start_client.py
    stdin_open: true
    tty: true
    environment:
      - SSLKEYLOGFILE=/tls_keys/tls-secrets.log
    entrypoint: ["/bin/sh", "-c", "sleep 7 && python3 /app/start_client.py && tail -f /dev/null"]